# Generated by Django 4.0.5 on 2022-07-03 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futbol', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liga',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
